language: ruby
rvm:
- 2.1.1
branches:
  only:
  - master
before_script:
- bundle update transam_core
- cp spec/dummy/config/database.travis.yml spec/dummy/config/database.yml
script:
- bundle exec rake app:transam_lib:prepare_rspec
- bundle exec rspec
before_install:
- mysql -e "create database IF NOT EXISTS transam_lib_testing;" -uroot
